-- ⚠️ Fichier IDENTIQUE (même nom, même contenu) à
-- gestion-americanfullfightingbons/migrations/0015_adherent_inscription_pdf.sql
--
-- Pourquoi ce fichier existe aussi ici : les 6 workers AFFBC partagent une
-- seule base D1 (affbc-production), mais chaque dépôt a son propre dossier
-- migrations/ et donc sa propre numérotation. Le worker "gestion" a déjà
-- appliqué cette migration en production (colonnes pdf_inscription_* sur
-- "adherents"), utilisées PAR CE WORKER (inscription) pour stocker le
-- bulletin d'inscription généré à la confirmation de paiement — cf.
-- src/routes/_lib/free-registration.js et
-- src/routes/api/public/payment/helloasso/status.js — mais qu'aucune
-- migration de CE dépôt ne créait avant ce fichier.
--
-- Le nom doit rester EXACTEMENT "0015_adherent_inscription_pdf.sql" :
-- `wrangler d1 migrations apply` suit les migrations déjà exécutées par nom
-- de fichier dans une table (d1_migrations) qui vit DANS la base D1
-- elle-même — donc partagée entre les 6 dépôts qui pointent vers la même
-- base. Comme "gestion" a déjà fait tourner ce nom-là en production,
-- `wrangler d1 migrations apply DB --remote` lancé depuis CE dépôt le verra
-- déjà appliqué et l'ignorera (aucun risque de "duplicate column"). Sur une
-- base neuve (D1 locale de dev, restauration après incident, nouvel
-- environnement), il s'exécutera normalement et créera les colonnes.
--
-- Renommer ce fichier casserait cette détection et provoquerait une erreur
-- "duplicate column name" au prochain déploiement en production.
--
-- Sépare le PDF généré automatiquement à l'inscription (bulletin d'inscription,
-- rempli par le worker inscription-americanfullfightingbons à la confirmation
-- du paiement HelloAsso ou d'une inscription gratuite) de la fiche de notation
-- (PDF téléversé manuellement par un coach/secrétaire depuis gestion).
--
-- Avant cette migration, les deux documents partageaient les mêmes colonnes
-- (pdf_storage_path / pdf_public_url / pdf_nom_fichier / pdf_uploaded_at) sur
-- "adherents" : le worker inscription écrasait systématiquement ces colonnes
-- à chaque inscription ou renouvellement (y compris en les remettant à NULL
-- avant de les repositionner), effaçant silencieusement toute fiche de
-- notation déjà enregistrée — et inversement, un nouveau téléversement de
-- fiche de notation faisait perdre le lien vers le bulletin d'inscription.
--
-- pdf_storage_path / pdf_public_url / pdf_nom_fichier / pdf_uploaded_at
-- restent désormais réservés à la fiche de notation (gestion uniquement).
-- pdf_inscription_* sont réservés au bulletin d'inscription (inscription-web
-- uniquement).
ALTER TABLE adherents ADD COLUMN pdf_inscription_storage_path TEXT;
ALTER TABLE adherents ADD COLUMN pdf_inscription_public_url TEXT;
ALTER TABLE adherents ADD COLUMN pdf_inscription_nom_fichier TEXT;
ALTER TABLE adherents ADD COLUMN pdf_inscription_uploaded_at TEXT;
